name: Test

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: Test frpc
        run: |
            ./install.sh frpc
            ./uninstall.sh frpc

      - name: Test frps
        run: |
            ./install.sh frps
            ./uninstall.sh frps
