name: Test

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: Install deps
        run: |
          sudo apt-get install wget -y

      - name: Unit Test
        run: |
            bash ./run-tests.sh
